// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: good.proto

package goodclient

import (
	"context"

	"Server_gozero/CS/commodityServer/good/rpc/good"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetGoodRepReq  = good.GetGoodRepReq
	GetGoodRepResp = good.GetGoodRepResp

	Good interface {
		GetGood(ctx context.Context, in *GetGoodRepReq, opts ...grpc.CallOption) (*GetGoodRepResp, error)
	}

	defaultGood struct {
		cli zrpc.Client
	}
)

func NewGood(cli zrpc.Client) Good {
	return &defaultGood{
		cli: cli,
	}
}

func (m *defaultGood) GetGood(ctx context.Context, in *GetGoodRepReq, opts ...grpc.CallOption) (*GetGoodRepResp, error) {
	client := good.NewGoodClient(m.cli.Conn())
	return client.GetGood(ctx, in, opts...)
}
