// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: land.proto

package landclient

import (
	"context"

	"Server_gozero/CS/commodityServer/land/rpc/land"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetLandRepReq  = land.GetLandRepReq
	GetLandRepResp = land.GetLandRepResp

	Land interface {
		GetLand(ctx context.Context, in *GetLandRepReq, opts ...grpc.CallOption) (*GetLandRepResp, error)
	}

	defaultLand struct {
		cli zrpc.Client
	}
)

func NewLand(cli zrpc.Client) Land {
	return &defaultLand{
		cli: cli,
	}
}

func (m *defaultLand) GetLand(ctx context.Context, in *GetLandRepReq, opts ...grpc.CallOption) (*GetLandRepResp, error) {
	client := land.NewLandClient(m.cli.Conn())
	return client.GetLand(ctx, in, opts...)
}
