// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type LoginRequest struct {
	PhoneNumber string `json:"phone_number"`
	Password    string `json:"password"`
}

type LoginResponse struct {
	Code         int      `json:"code"`
	Msg          string   `json:"msg"`
	Userinfo     UserInfo `json:"user_info"`
	AccessToken  string   `json:"accessToken"`
	AccessExpire int      `json:"accessExpire"`
	RefreshAfter int      `json:"refreshAfter"`
}

type RegisterRequest struct {
	PhoneNumber string `json:"phone_number"`
	Nickname    string `json:"nickname"`
	Password    string `json:"password"`
}

type RegisterResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateAvatarRequest struct {
	UserID int `form:"user_id"`
}

type UpdateAvatarResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateUserInfoRequest struct {
	Userinfo UserInfo `json:"user_info"`
}

type UpdateUserInfoResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UserInfo struct {
	UserID      int    `json:"user_id"`
	PhoneNumber string `json:"phone_number"`
	Avatar      string `json:"avatar"`
	NickName    string `json:"nickname"`
	Address     string `json:"address"`
	Gender      int    `json:"gender"`
}
