// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6-devel
// 	protoc        v5.27.3
// source: BS.proto

package BSRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserReq) Reset() {
	*x = AddUserReq{}
	mi := &file_BS_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserReq) ProtoMessage() {}

func (x *AddUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_BS_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserReq.ProtoReflect.Descriptor instead.
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return file_BS_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResp) Reset() {
	*x = AddUserResp{}
	mi := &file_BS_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResp) ProtoMessage() {}

func (x *AddUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_BS_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResp.ProtoReflect.Descriptor instead.
func (*AddUserResp) Descriptor() ([]byte, []int) {
	return file_BS_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddUserResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddLandDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmId        int64                  `protobuf:"varint,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	LandSaleCount float64                `protobuf:"fixed64,2,opt,name=land_sale_count,json=landSaleCount,proto3" json:"land_sale_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLandDataReq) Reset() {
	*x = AddLandDataReq{}
	mi := &file_BS_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLandDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLandDataReq) ProtoMessage() {}

func (x *AddLandDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_BS_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLandDataReq.ProtoReflect.Descriptor instead.
func (*AddLandDataReq) Descriptor() ([]byte, []int) {
	return file_BS_proto_rawDescGZIP(), []int{2}
}

func (x *AddLandDataReq) GetFarmId() int64 {
	if x != nil {
		return x.FarmId
	}
	return 0
}

func (x *AddLandDataReq) GetLandSaleCount() float64 {
	if x != nil {
		return x.LandSaleCount
	}
	return 0
}

type AddLandDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLandDataResp) Reset() {
	*x = AddLandDataResp{}
	mi := &file_BS_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLandDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLandDataResp) ProtoMessage() {}

func (x *AddLandDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_BS_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLandDataResp.ProtoReflect.Descriptor instead.
func (*AddLandDataResp) Descriptor() ([]byte, []int) {
	return file_BS_proto_rawDescGZIP(), []int{3}
}

func (x *AddLandDataResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddLandDataResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddGoodDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmId        int64                  `protobuf:"varint,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	GoodSaleCount float64                `protobuf:"fixed64,2,opt,name=good_sale_count,json=goodSaleCount,proto3" json:"good_sale_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodDataReq) Reset() {
	*x = AddGoodDataReq{}
	mi := &file_BS_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodDataReq) ProtoMessage() {}

func (x *AddGoodDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_BS_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodDataReq.ProtoReflect.Descriptor instead.
func (*AddGoodDataReq) Descriptor() ([]byte, []int) {
	return file_BS_proto_rawDescGZIP(), []int{4}
}

func (x *AddGoodDataReq) GetFarmId() int64 {
	if x != nil {
		return x.FarmId
	}
	return 0
}

func (x *AddGoodDataReq) GetGoodSaleCount() float64 {
	if x != nil {
		return x.GoodSaleCount
	}
	return 0
}

type AddGoodDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodDataResp) Reset() {
	*x = AddGoodDataResp{}
	mi := &file_BS_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodDataResp) ProtoMessage() {}

func (x *AddGoodDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_BS_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodDataResp.ProtoReflect.Descriptor instead.
func (*AddGoodDataResp) Descriptor() ([]byte, []int) {
	return file_BS_proto_rawDescGZIP(), []int{5}
}

func (x *AddGoodDataResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddGoodDataResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_BS_proto protoreflect.FileDescriptor

const file_BS_proto_rawDesc = "" +
	"\n" +
	"\bBS.proto\x12\x05BSRPC\"%\n" +
	"\n" +
	"addUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"3\n" +
	"\vaddUserResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"Q\n" +
	"\x0eaddLandDataReq\x12\x17\n" +
	"\afarm_id\x18\x01 \x01(\x03R\x06farmId\x12&\n" +
	"\x0fland_sale_count\x18\x02 \x01(\x01R\rlandSaleCount\"7\n" +
	"\x0faddLandDataResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"Q\n" +
	"\x0eaddGoodDataReq\x12\x17\n" +
	"\afarm_id\x18\x01 \x01(\x03R\x06farmId\x12&\n" +
	"\x0fgood_sale_count\x18\x02 \x01(\x01R\rgoodSaleCount\"7\n" +
	"\x0faddGoodDataResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xb2\x01\n" +
	"\x02BS\x120\n" +
	"\aaddUser\x12\x11.BSRPC.addUserReq\x1a\x12.BSRPC.addUserResp\x12<\n" +
	"\vaddLandData\x12\x15.BSRPC.addLandDataReq\x1a\x16.BSRPC.addLandDataResp\x12<\n" +
	"\vaddGoodData\x12\x15.BSRPC.addGoodDataReq\x1a\x16.BSRPC.addGoodDataRespB\tZ\a./BSRPCb\x06proto3"

var (
	file_BS_proto_rawDescOnce sync.Once
	file_BS_proto_rawDescData []byte
)

func file_BS_proto_rawDescGZIP() []byte {
	file_BS_proto_rawDescOnce.Do(func() {
		file_BS_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BS_proto_rawDesc), len(file_BS_proto_rawDesc)))
	})
	return file_BS_proto_rawDescData
}

var file_BS_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_BS_proto_goTypes = []any{
	(*AddUserReq)(nil),      // 0: BSRPC.addUserReq
	(*AddUserResp)(nil),     // 1: BSRPC.addUserResp
	(*AddLandDataReq)(nil),  // 2: BSRPC.addLandDataReq
	(*AddLandDataResp)(nil), // 3: BSRPC.addLandDataResp
	(*AddGoodDataReq)(nil),  // 4: BSRPC.addGoodDataReq
	(*AddGoodDataResp)(nil), // 5: BSRPC.addGoodDataResp
}
var file_BS_proto_depIdxs = []int32{
	0, // 0: BSRPC.BS.addUser:input_type -> BSRPC.addUserReq
	2, // 1: BSRPC.BS.addLandData:input_type -> BSRPC.addLandDataReq
	4, // 2: BSRPC.BS.addGoodData:input_type -> BSRPC.addGoodDataReq
	1, // 3: BSRPC.BS.addUser:output_type -> BSRPC.addUserResp
	3, // 4: BSRPC.BS.addLandData:output_type -> BSRPC.addLandDataResp
	5, // 5: BSRPC.BS.addGoodData:output_type -> BSRPC.addGoodDataResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_BS_proto_init() }
func file_BS_proto_init() {
	if File_BS_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BS_proto_rawDesc), len(file_BS_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_BS_proto_goTypes,
		DependencyIndexes: file_BS_proto_depIdxs,
		MessageInfos:      file_BS_proto_msgTypes,
	}.Build()
	File_BS_proto = out.File
	file_BS_proto_goTypes = nil
	file_BS_proto_depIdxs = nil
}
