// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"api/internal/svc"
	"net/http"


	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/updateAvatar",
				Handler: UpdateAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uploadUserInfo",
				Handler: UploadUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/userLogin",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/userRegister",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
