// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: ISender.proto

package ISender

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ID_GetID_FullMethodName = "/ID.ID/getID"
)

// IDClient is the client API for ID service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDClient interface {
	GetID(ctx context.Context, in *GetIDReq, opts ...grpc.CallOption) (*GetIDResp, error)
}

type iDClient struct {
	cc grpc.ClientConnInterface
}

func NewIDClient(cc grpc.ClientConnInterface) IDClient {
	return &iDClient{cc}
}

func (c *iDClient) GetID(ctx context.Context, in *GetIDReq, opts ...grpc.CallOption) (*GetIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIDResp)
	err := c.cc.Invoke(ctx, ID_GetID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDServer is the server API for ID service.
// All implementations must embed UnimplementedIDServer
// for forward compatibility.
type IDServer interface {
	GetID(context.Context, *GetIDReq) (*GetIDResp, error)
	mustEmbedUnimplementedIDServer()
}

// UnimplementedIDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIDServer struct{}

func (UnimplementedIDServer) GetID(context.Context, *GetIDReq) (*GetIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetID not implemented")
}
func (UnimplementedIDServer) mustEmbedUnimplementedIDServer() {}
func (UnimplementedIDServer) testEmbeddedByValue()            {}

// UnsafeIDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDServer will
// result in compilation errors.
type UnsafeIDServer interface {
	mustEmbedUnimplementedIDServer()
}

func RegisterIDServer(s grpc.ServiceRegistrar, srv IDServer) {
	// If the following call pancis, it indicates UnimplementedIDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ID_ServiceDesc, srv)
}

func _ID_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ID_GetID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServer).GetID(ctx, req.(*GetIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ID_ServiceDesc is the grpc.ServiceDesc for ID service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ID_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ID.ID",
	HandlerType: (*IDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getID",
			Handler:    _ID_GetID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ISender.proto",
}
