// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"Server_gozero/CS/orderServer/LandOrder/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/AddLandOrder",
				Handler: AddLandOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetLandOrder",
				Handler: GetLandOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetLandOrderDetail",
				Handler: GetLandOrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetOrderByStatus",
				Handler: GetOrderByStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/UpdateOrderCount",
				Handler: UpdateOrderCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
