// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6-devel
// 	protoc        v5.27.3
// source: ISender.proto

package ISender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizTag        string                 `protobuf:"bytes,1,opt,name=bizTag,proto3" json:"bizTag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIDReq) Reset() {
	*x = GetIDReq{}
	mi := &file_ISender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDReq) ProtoMessage() {}

func (x *GetIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_ISender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDReq.ProtoReflect.Descriptor instead.
func (*GetIDReq) Descriptor() ([]byte, []int) {
	return file_ISender_proto_rawDescGZIP(), []int{0}
}

func (x *GetIDReq) GetBizTag() string {
	if x != nil {
		return x.BizTag
	}
	return ""
}

type GetIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizTag        string                 `protobuf:"bytes,1,opt,name=bizTag,proto3" json:"bizTag,omitempty"`
	IdStart       int64                  `protobuf:"varint,2,opt,name=idStart,proto3" json:"idStart,omitempty"`
	IdEnd         int64                  `protobuf:"varint,3,opt,name=idEnd,proto3" json:"idEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIDResp) Reset() {
	*x = GetIDResp{}
	mi := &file_ISender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDResp) ProtoMessage() {}

func (x *GetIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_ISender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDResp.ProtoReflect.Descriptor instead.
func (*GetIDResp) Descriptor() ([]byte, []int) {
	return file_ISender_proto_rawDescGZIP(), []int{1}
}

func (x *GetIDResp) GetBizTag() string {
	if x != nil {
		return x.BizTag
	}
	return ""
}

func (x *GetIDResp) GetIdStart() int64 {
	if x != nil {
		return x.IdStart
	}
	return 0
}

func (x *GetIDResp) GetIdEnd() int64 {
	if x != nil {
		return x.IdEnd
	}
	return 0
}

var File_ISender_proto protoreflect.FileDescriptor

const file_ISender_proto_rawDesc = "" +
	"\n" +
	"\rISender.proto\x12\x02ID\"\"\n" +
	"\bgetIDReq\x12\x16\n" +
	"\x06bizTag\x18\x01 \x01(\tR\x06bizTag\"S\n" +
	"\tgetIDResp\x12\x16\n" +
	"\x06bizTag\x18\x01 \x01(\tR\x06bizTag\x12\x18\n" +
	"\aidStart\x18\x02 \x01(\x03R\aidStart\x12\x14\n" +
	"\x05idEnd\x18\x03 \x01(\x03R\x05idEnd2*\n" +
	"\x02ID\x12$\n" +
	"\x05getID\x12\f.ID.getIDReq\x1a\r.ID.getIDRespB\vZ\t./ISenderb\x06proto3"

var (
	file_ISender_proto_rawDescOnce sync.Once
	file_ISender_proto_rawDescData []byte
)

func file_ISender_proto_rawDescGZIP() []byte {
	file_ISender_proto_rawDescOnce.Do(func() {
		file_ISender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ISender_proto_rawDesc), len(file_ISender_proto_rawDesc)))
	})
	return file_ISender_proto_rawDescData
}

var file_ISender_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ISender_proto_goTypes = []any{
	(*GetIDReq)(nil),  // 0: ID.getIDReq
	(*GetIDResp)(nil), // 1: ID.getIDResp
}
var file_ISender_proto_depIdxs = []int32{
	0, // 0: ID.ID.getID:input_type -> ID.getIDReq
	1, // 1: ID.ID.getID:output_type -> ID.getIDResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ISender_proto_init() }
func file_ISender_proto_init() {
	if File_ISender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ISender_proto_rawDesc), len(file_ISender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ISender_proto_goTypes,
		DependencyIndexes: file_ISender_proto_depIdxs,
		MessageInfos:      file_ISender_proto_msgTypes,
	}.Build()
	File_ISender_proto = out.File
	file_ISender_proto_goTypes = nil
	file_ISender_proto_depIdxs = nil
}
