// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6-devel
// 	protoc        v5.27.3
// source: commodity.proto

package commodity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGoodRepReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodID        int64                  `protobuf:"varint,1,opt,name=GoodID,proto3" json:"GoodID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodRepReq) Reset() {
	*x = GetGoodRepReq{}
	mi := &file_commodity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodRepReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodRepReq) ProtoMessage() {}

func (x *GetGoodRepReq) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodRepReq.ProtoReflect.Descriptor instead.
func (*GetGoodRepReq) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{0}
}

func (x *GetGoodRepReq) GetGoodID() int64 {
	if x != nil {
		return x.GoodID
	}
	return 0
}

type GetGoodRepResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repertory     int64                  `protobuf:"varint,1,opt,name=repertory,proto3" json:"repertory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodRepResp) Reset() {
	*x = GetGoodRepResp{}
	mi := &file_commodity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodRepResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodRepResp) ProtoMessage() {}

func (x *GetGoodRepResp) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodRepResp.ProtoReflect.Descriptor instead.
func (*GetGoodRepResp) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{1}
}

func (x *GetGoodRepResp) GetRepertory() int64 {
	if x != nil {
		return x.Repertory
	}
	return 0
}

type UpdateRepReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodID        int64                  `protobuf:"varint,1,opt,name=GoodID,proto3" json:"GoodID,omitempty"`
	Repertory     int64                  `protobuf:"varint,2,opt,name=repertory,proto3" json:"repertory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepReq) Reset() {
	*x = UpdateRepReq{}
	mi := &file_commodity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepReq) ProtoMessage() {}

func (x *UpdateRepReq) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepReq.ProtoReflect.Descriptor instead.
func (*UpdateRepReq) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRepReq) GetGoodID() int64 {
	if x != nil {
		return x.GoodID
	}
	return 0
}

func (x *UpdateRepReq) GetRepertory() int64 {
	if x != nil {
		return x.Repertory
	}
	return 0
}

type UpdateRepResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepResp) Reset() {
	*x = UpdateRepResp{}
	mi := &file_commodity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepResp) ProtoMessage() {}

func (x *UpdateRepResp) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepResp.ProtoReflect.Descriptor instead.
func (*UpdateRepResp) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{3}
}

type GetLandRepReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandID        int64                  `protobuf:"varint,1,opt,name=LandID,proto3" json:"LandID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLandRepReq) Reset() {
	*x = GetLandRepReq{}
	mi := &file_commodity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLandRepReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLandRepReq) ProtoMessage() {}

func (x *GetLandRepReq) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLandRepReq.ProtoReflect.Descriptor instead.
func (*GetLandRepReq) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{4}
}

func (x *GetLandRepReq) GetLandID() int64 {
	if x != nil {
		return x.LandID
	}
	return 0
}

type GetLandRepResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaleStatus    int64                  `protobuf:"varint,1,opt,name=sale_status,json=saleStatus,proto3" json:"sale_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLandRepResp) Reset() {
	*x = GetLandRepResp{}
	mi := &file_commodity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLandRepResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLandRepResp) ProtoMessage() {}

func (x *GetLandRepResp) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLandRepResp.ProtoReflect.Descriptor instead.
func (*GetLandRepResp) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{5}
}

func (x *GetLandRepResp) GetSaleStatus() int64 {
	if x != nil {
		return x.SaleStatus
	}
	return 0
}

type UpdateStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandID        int64                  `protobuf:"varint,1,opt,name=LandID,proto3" json:"LandID,omitempty"`
	SaleStatus    int64                  `protobuf:"varint,2,opt,name=sale_status,json=saleStatus,proto3" json:"sale_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusReq) Reset() {
	*x = UpdateStatusReq{}
	mi := &file_commodity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReq) ProtoMessage() {}

func (x *UpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStatusReq) GetLandID() int64 {
	if x != nil {
		return x.LandID
	}
	return 0
}

func (x *UpdateStatusReq) GetSaleStatus() int64 {
	if x != nil {
		return x.SaleStatus
	}
	return 0
}

type UpdateStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResp) Reset() {
	*x = UpdateStatusResp{}
	mi := &file_commodity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResp) ProtoMessage() {}

func (x *UpdateStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateStatusResp) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{7}
}

var File_commodity_proto protoreflect.FileDescriptor

const file_commodity_proto_rawDesc = "" +
	"\n" +
	"\x0fcommodity.proto\x12\tcommodity\"'\n" +
	"\rgetGoodRepReq\x12\x16\n" +
	"\x06GoodID\x18\x01 \x01(\x03R\x06GoodID\".\n" +
	"\x0egetGoodRepResp\x12\x1c\n" +
	"\trepertory\x18\x01 \x01(\x03R\trepertory\"D\n" +
	"\fupdateRepReq\x12\x16\n" +
	"\x06GoodID\x18\x01 \x01(\x03R\x06GoodID\x12\x1c\n" +
	"\trepertory\x18\x02 \x01(\x03R\trepertory\"\x0f\n" +
	"\rupdateRepResp\"'\n" +
	"\rgetLandRepReq\x12\x16\n" +
	"\x06LandID\x18\x01 \x01(\x03R\x06LandID\"1\n" +
	"\x0egetLandRepResp\x12\x1f\n" +
	"\vsale_status\x18\x01 \x01(\x03R\n" +
	"saleStatus\"J\n" +
	"\x0fupdateStatusReq\x12\x16\n" +
	"\x06LandID\x18\x01 \x01(\x03R\x06LandID\x12\x1f\n" +
	"\vsale_status\x18\x02 \x01(\x03R\n" +
	"saleStatus\"\x12\n" +
	"\x10updateStatusResp2\x94\x02\n" +
	"\tcommodity\x12>\n" +
	"\agetGood\x12\x18.commodity.getGoodRepReq\x1a\x19.commodity.getGoodRepResp\x12>\n" +
	"\tupdateRep\x12\x17.commodity.updateRepReq\x1a\x18.commodity.updateRepResp\x12>\n" +
	"\agetLand\x12\x18.commodity.getLandRepReq\x1a\x19.commodity.getLandRepResp\x12G\n" +
	"\fupdateStatus\x12\x1a.commodity.updateStatusReq\x1a\x1b.commodity.updateStatusRespB\rZ\v./commodityb\x06proto3"

var (
	file_commodity_proto_rawDescOnce sync.Once
	file_commodity_proto_rawDescData []byte
)

func file_commodity_proto_rawDescGZIP() []byte {
	file_commodity_proto_rawDescOnce.Do(func() {
		file_commodity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commodity_proto_rawDesc), len(file_commodity_proto_rawDesc)))
	})
	return file_commodity_proto_rawDescData
}

var file_commodity_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_commodity_proto_goTypes = []any{
	(*GetGoodRepReq)(nil),    // 0: commodity.getGoodRepReq
	(*GetGoodRepResp)(nil),   // 1: commodity.getGoodRepResp
	(*UpdateRepReq)(nil),     // 2: commodity.updateRepReq
	(*UpdateRepResp)(nil),    // 3: commodity.updateRepResp
	(*GetLandRepReq)(nil),    // 4: commodity.getLandRepReq
	(*GetLandRepResp)(nil),   // 5: commodity.getLandRepResp
	(*UpdateStatusReq)(nil),  // 6: commodity.updateStatusReq
	(*UpdateStatusResp)(nil), // 7: commodity.updateStatusResp
}
var file_commodity_proto_depIdxs = []int32{
	0, // 0: commodity.commodity.getGood:input_type -> commodity.getGoodRepReq
	2, // 1: commodity.commodity.updateRep:input_type -> commodity.updateRepReq
	4, // 2: commodity.commodity.getLand:input_type -> commodity.getLandRepReq
	6, // 3: commodity.commodity.updateStatus:input_type -> commodity.updateStatusReq
	1, // 4: commodity.commodity.getGood:output_type -> commodity.getGoodRepResp
	3, // 5: commodity.commodity.updateRep:output_type -> commodity.updateRepResp
	5, // 6: commodity.commodity.getLand:output_type -> commodity.getLandRepResp
	7, // 7: commodity.commodity.updateStatus:output_type -> commodity.updateStatusResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commodity_proto_init() }
func file_commodity_proto_init() {
	if File_commodity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commodity_proto_rawDesc), len(file_commodity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commodity_proto_goTypes,
		DependencyIndexes: file_commodity_proto_depIdxs,
		MessageInfos:      file_commodity_proto_msgTypes,
	}.Build()
	File_commodity_proto = out.File
	file_commodity_proto_goTypes = nil
	file_commodity_proto_depIdxs = nil
}
