// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: ISender.proto

package idClient

import (
	"context"

	"Server_gozero/master/ISender/rpc/ISender"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetIDReq  = ISender.GetIDReq
	GetIDResp = ISender.GetIDResp

	User interface {
		GetID(ctx context.Context, in *GetIDReq, opts ...grpc.CallOption) (*GetIDResp, error)
	}

	defaultID struct {
		cli zrpc.Client
	}
)

func NewID(cli zrpc.Client) User {
	return &defaultID{
		cli: cli,
	}
}

func (m *defaultID) GetID(ctx context.Context, in *GetIDReq, opts ...grpc.CallOption) (*GetIDResp, error) {
	client := ISender.NewIDClient(m.cli.Conn())
	return client.GetID(ctx, in, opts...)
}
