// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AddGoodOrder struct {
	ImageUrls   string  `json:"image_urls"`   // 图片信息（JSON字符串或逗号分隔）
	GoodId      int64   `json:"good_id"`      // 关联商品ID
	FarmId      int64   `json:"farm_id"`      // 商品所属农场ID
	UserId      int64   `json:"user_id"`      // 关联用户ID
	UserAddress string  `json:"user_address"` // 用户所在地址
	FarmAddress string  `json:"farm_address"` // 农场所在地址
	Price       float64 `json:"price"`        // 价格
	Units       string  `json:"units"`        // 单位（个/斤/千克等）
	Count       int64   `json:"count"`        // 购买数量
	Detail      string  `json:"detail"`       // 订单详情
	OrderStatus string  `json:"order_status"`
}

type AddGoodOrderRequest struct {
	Good_order AddGoodOrder `json:"good_order"`
}

type AddGoodOrderResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type AddLandOrder struct {
	ImageUrls   string  `json:"image_urls"`   // 图片信息
	LandId      int64   `json:"land_id"`      // 关联土地ID
	FarmId      int64   `json:"farm_id"`      // 所属农场ID
	UserId      int64   `json:"user_id"`      // 用户ID
	FarmAddress string  `json:"farm_address"` // 农场地址
	Price       float64 `json:"price"`        // 租赁价格
	Count       int64   `json:"count"`        // 租赁时长
	Detail      string  `json:"detail"`       // 订单详情
	OrderStatus string  `json:"order_status"`
}

type AddLandOrderRequest struct {
	Land_order AddLandOrder `json:"land_order"`
}

type AddLandOrderResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type GetGoodOrderByStatusRequest struct {
	UserID      int    `json:"user_id"`
	OrderStatus string `json:"order_status"`
}

type GetGoodOrderByStatusResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Good_order []*GoodOrder `json:"good_order"`
}

type GetGoodOrderDetailRequest struct {
	UserID      int `json:"user_id"`
	GoodOrderID int `json:"good_order_id"`
}

type GetGoodOrderDetailResponse struct {
	Code       int       `json:"code"`       // 状态码
	Msg        string    `json:"msg"`        // 响应信息
	Good_order GoodOrder `json:"good_order"` // 商品列表
}

type GetGoodOrderRequest struct {
	UserID int `json:"user_id"`
}

type GetGoodOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Good_order []*GoodOrder `json:"good_order"`
}

type GetLandOrderByStatusRequest struct {
	UserID      int    `json:"user_id"`
	OrderStatus string `json:"order_status"`
}

type GetLandOrderByStatusResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Land_order []*LandOrder `json:"land_order"`
}

type GetLandOrderDetailRequest struct {
	UserID      int `json:"user_id"`
	LandOrderID int `json:"land_order_id"`
}

type GetLandOrderDetailResponse struct {
	Code       int       `json:"code"`       // 状态码
	Msg        string    `json:"msg"`        // 响应信息
	Land_order LandOrder `json:"land_order"` // 商品列表
}

type GetLandOrderRequest struct {
	UserID int `json:"user_id"`
}

type GetLandOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Land_order []*LandOrder `json:"land_order"`
}

type GoodOrder struct {
	Id          int64   `json:"id"`
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	GoodOrderId int64   `json:"good_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息（JSON字符串或逗号分隔）
	GoodId      int64   `json:"good_id"`       // 关联商品ID
	FarmId      int64   `json:"farm_id"`       // 商品所属农场ID
	UserId      int64   `json:"user_id"`       // 关联用户ID
	UserAddress string  `json:"user_address"`  // 用户所在地址
	FarmAddress string  `json:"farm_address"`  // 农场所在地址
	Price       float64 `json:"price"`         // 价格
	Units       string  `json:"units"`         // 单位（个/斤/千克等）
	Count       int64   `json:"count"`         // 购买数量
	Detail      string  `json:"detail"`        // 订单详情
	OrderStatus string  `json:"order_status"`
}

type LandOrder struct {
	Id          int64   `json:"id"`            // 主键ID
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	LandOrderId int64   `json:"land_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息
	LandId      int64   `json:"land_id"`       // 关联土地ID
	FarmId      int64   `json:"farm_id"`       // 所属农场ID
	UserId      int64   `json:"user_id"`       // 用户ID
	FarmAddress string  `json:"farm_address"`  // 农场地址
	Price       float64 `json:"price"`         // 租赁价格
	Count       int64   `json:"count"`         // 租赁时长
	Detail      string  `json:"detail"`        // 订单详情
	OrderStatus string  `json:"order_status"`
}

type UpdateGoodOrderCountRequest struct {
	GoodOrderID int `json:"good_order_id"`
	UserID      int `json:"user_id"`
	Count       int `json:"count"`
}

type UpdateGoodOrderCountResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateLandOrderCountRequest struct {
	LandOrderID int `json:"land_order_id"`
	UserID      int `json:"user_id"`
	Count       int `json:"count"`
}

type UpdateLandOrderCountResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
