// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AddGoodOrder struct {
	ImageUrls   string  `json:"image_urls"`   // 图片信息（JSON字符串或逗号分隔）
	GoodId      int64   `json:"good_id"`      // 关联商品ID
	FarmId      int64   `json:"farm_id"`      // 商品所属农场ID
	UserId      int64   `json:"user_id"`      // 关联用户ID
	UserAddress string  `json:"user_address"` // 用户所在地址
	FarmAddress string  `json:"farm_address"` // 农场所在地址
	Price       float64 `json:"price"`        // 价格
	Units       string  `json:"units"`        // 单位（个/斤/千克等）
	Count       int64   `json:"count"`        // 购买数量
	Detail      string  `json:"detail"`       // 订单详情
	OrderStatus string  `json:"order_status"`
}

type AddGoodOrderRequest struct {
	Good_order AddGoodOrder `json:"good_order"`
}

type AddGoodOrderResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type AddLandOrder struct {
	ImageUrls   string  `json:"image_urls"`   // 图片信息
	LandId      int64   `json:"land_id"`      // 关联土地ID
	FarmId      int64   `json:"farm_id"`      // 所属农场ID
	UserId      int64   `json:"user_id"`      // 用户ID
	FarmAddress string  `json:"farm_address"` // 农场地址
	Price       float64 `json:"price"`        // 租赁价格
	Count       int64   `json:"count"`        // 租赁时长
	Detail      string  `json:"detail"`       // 订单详情
	OrderStatus string  `json:"order_status"`
}

type AddLandOrderRequest struct {
	Land_order AddLandOrder `json:"land_order"`
}

type AddLandOrderResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Amount struct {
	Total    int    `json:"total"`
	Currency string `json:"currency"`
}

type Detail struct {
	CostPrice   int         `json:"cost_price"`
	InvoiceID   string      `json:"invoice_id"`
	GoodsDetail GoodsDetail `json:"goods_detail"`
}

type GetGoodOrderByStatusRequest struct {
	UserID      int    `json:"user_id"`
	OrderStatus string `json:"order_status"`
}

type GetGoodOrderByStatusResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Good_order []*GoodOrder `json:"good_order"`
}

type GetGoodOrderDetailRequest struct {
	UserID      int `json:"user_id"`
	GoodOrderID int `json:"good_order_id"`
}

type GetGoodOrderDetailResponse struct {
	Code       int       `json:"code"`       // 状态码
	Msg        string    `json:"msg"`        // 响应信息
	Good_order GoodOrder `json:"good_order"` // 商品列表
}

type GetGoodOrderRequest struct {
	UserID int `json:"user_id"`
}

type GetGoodOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Good_order []*GoodOrder `json:"good_order"`
}

type GetLandOrderByStatusRequest struct {
	UserID      int    `json:"user_id"`
	OrderStatus string `json:"order_status"`
}

type GetLandOrderByStatusResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Land_order []*LandOrder `json:"land_order"`
}

type GetLandOrderDetailRequest struct {
	UserID      int `json:"user_id"`
	LandOrderID int `json:"land_order_id"`
}

type GetLandOrderDetailResponse struct {
	Code       int       `json:"code"`       // 状态码
	Msg        string    `json:"msg"`        // 响应信息
	Land_order LandOrder `json:"land_order"` // 商品列表
}

type GetLandOrderRequest struct {
	UserID int `json:"user_id"`
}

type GetLandOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Land_order []*LandOrder `json:"land_order"`
}

type GoodOrder struct {
	Id          int64   `json:"id"`
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	GoodOrderId int64   `json:"good_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息（JSON字符串或逗号分隔）
	GoodId      int64   `json:"good_id"`       // 关联商品ID
	FarmId      int64   `json:"farm_id"`       // 商品所属农场ID
	UserId      int64   `json:"user_id"`       // 关联用户ID
	UserAddress string  `json:"user_address"`  // 用户所在地址
	FarmAddress string  `json:"farm_address"`  // 农场所在地址
	Price       float64 `json:"price"`         // 价格
	Units       string  `json:"units"`         // 单位（个/斤/千克等）
	Count       int64   `json:"count"`         // 购买数量
	Detail      string  `json:"detail"`        // 订单详情
	OrderStatus string  `json:"order_status"`
}

type GoodsDetail struct {
	MerchantGoodsID  string `json:"merchant_goods_id"`
	WechatpayGoodsID string `json:"wechatpay_goods_id"`
	GoodsName        string `json:"goods_name"`
	Quantity         int    `json:"quantity"`
	UnitPrice        int    `json:"unit_price"`
}

type LandOrder struct {
	Id          int64   `json:"id"`            // 主键ID
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	LandOrderId int64   `json:"land_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息
	LandId      int64   `json:"land_id"`       // 关联土地ID
	FarmId      int64   `json:"farm_id"`       // 所属农场ID
	UserId      int64   `json:"user_id"`       // 用户ID
	FarmAddress string  `json:"farm_address"`  // 农场地址
	Price       float64 `json:"price"`         // 租赁价格
	Count       int64   `json:"count"`         // 租赁时长
	Detail      string  `json:"detail"`        // 订单详情
	OrderStatus string  `json:"order_status"`
}

type Payer struct {
	OpenID string `json:"openid"`
}

type SceneInfo struct {
	PayerClientIP string    `json:"payer_client_ip"`
	DeviceID      string    `json:"device_id"`
	StoreInfo     StoreInfo `json:"store_info"`
}

type SettleInfo struct {
	ProfitSharing bool `json:"profit_sharing"`
}

type StoreInfo struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	AreaCode string `json:"area_code"`
	Address  string `json:"address"`
}

type UpdateGoodOrderCountRequest struct {
	GoodOrderID int `json:"good_order_id"`
	UserID      int `json:"user_id"`
	Count       int `json:"count"`
}

type UpdateGoodOrderCountResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateLandOrderCountRequest struct {
	LandOrderID int `json:"land_order_id"`
	UserID      int `json:"user_id"`
	Count       int `json:"count"`
}

type UpdateLandOrderCountResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type WechatOrderRequest struct {
	AppID         string     `json:"appid"`
	MchID         string     `json:"mchid"`
	Description   string     `json:"description"`
	OutTradeNo    string     `json:"out_trade_no"`
	TimeExpire    string     `json:"time_expire"`
	Attach        string     `json:"attach"`
	NotifyUrl     string     `json:"notify_url"`
	GoodsTag      string     `json:"goods_tag"`
	SupportFapiao bool       `json:"support_fapiao"`
	Amount        Amount     `json:"amount"`
	Payer         Payer      `json:"payer"`
	Detail        Detail     `json:"detail"`
	SceneInfo     SceneInfo  `json:"scene_info"`
	SettleInfo    SettleInfo `json:"settle_info"`
}

type WechatOrderResponse struct {
	TimeStamp string `json:"time_stamp"`
	NonceStr  string `json:"nonce_str"`
	Package   string `json:"package"`
	SignType  string `json:"sign_type"`
	PaySign   string `json:"pay_sign"`
}
