// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: land.proto

package land

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Land_GetLand_FullMethodName      = "/land.land/getLand"
	Land_UpdateStatus_FullMethodName = "/land.land/updateStatus"
)

// LandClient is the client API for Land service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LandClient interface {
	GetLand(ctx context.Context, in *GetLandRepReq, opts ...grpc.CallOption) (*GetLandRepResp, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*UpdateStatusResp, error)
}

type landClient struct {
	cc grpc.ClientConnInterface
}

func NewLandClient(cc grpc.ClientConnInterface) LandClient {
	return &landClient{cc}
}

func (c *landClient) GetLand(ctx context.Context, in *GetLandRepReq, opts ...grpc.CallOption) (*GetLandRepResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLandRepResp)
	err := c.cc.Invoke(ctx, Land_GetLand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landClient) UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*UpdateStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatusResp)
	err := c.cc.Invoke(ctx, Land_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LandServer is the server API for Land service.
// All implementations must embed UnimplementedLandServer
// for forward compatibility.
type LandServer interface {
	GetLand(context.Context, *GetLandRepReq) (*GetLandRepResp, error)
	UpdateStatus(context.Context, *UpdateStatusReq) (*UpdateStatusResp, error)
	mustEmbedUnimplementedLandServer()
}

// UnimplementedLandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLandServer struct{}

func (UnimplementedLandServer) GetLand(context.Context, *GetLandRepReq) (*GetLandRepResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLand not implemented")
}
func (UnimplementedLandServer) UpdateStatus(context.Context, *UpdateStatusReq) (*UpdateStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedLandServer) mustEmbedUnimplementedLandServer() {}
func (UnimplementedLandServer) testEmbeddedByValue()              {}

// UnsafeLandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LandServer will
// result in compilation errors.
type UnsafeLandServer interface {
	mustEmbedUnimplementedLandServer()
}

func RegisterLandServer(s grpc.ServiceRegistrar, srv LandServer) {
	// If the following call pancis, it indicates UnimplementedLandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Land_ServiceDesc, srv)
}

func _Land_GetLand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLandRepReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandServer).GetLand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Land_GetLand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandServer).GetLand(ctx, req.(*GetLandRepReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Land_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Land_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandServer).UpdateStatus(ctx, req.(*UpdateStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Land_ServiceDesc is the grpc.ServiceDesc for Land service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Land_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "land.land",
	HandlerType: (*LandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getLand",
			Handler:    _Land_GetLand_Handler,
		},
		{
			MethodName: "updateStatus",
			Handler:    _Land_UpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "land.proto",
}
