// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6-devel
// 	protoc        v5.27.3
// source: land.proto

package land

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLandRepReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandID        int64                  `protobuf:"varint,1,opt,name=LandID,proto3" json:"LandID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLandRepReq) Reset() {
	*x = GetLandRepReq{}
	mi := &file_land_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLandRepReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLandRepReq) ProtoMessage() {}

func (x *GetLandRepReq) ProtoReflect() protoreflect.Message {
	mi := &file_land_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLandRepReq.ProtoReflect.Descriptor instead.
func (*GetLandRepReq) Descriptor() ([]byte, []int) {
	return file_land_proto_rawDescGZIP(), []int{0}
}

func (x *GetLandRepReq) GetLandID() int64 {
	if x != nil {
		return x.LandID
	}
	return 0
}

type GetLandRepResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaleStatus    int64                  `protobuf:"varint,1,opt,name=sale_status,json=saleStatus,proto3" json:"sale_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLandRepResp) Reset() {
	*x = GetLandRepResp{}
	mi := &file_land_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLandRepResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLandRepResp) ProtoMessage() {}

func (x *GetLandRepResp) ProtoReflect() protoreflect.Message {
	mi := &file_land_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLandRepResp.ProtoReflect.Descriptor instead.
func (*GetLandRepResp) Descriptor() ([]byte, []int) {
	return file_land_proto_rawDescGZIP(), []int{1}
}

func (x *GetLandRepResp) GetSaleStatus() int64 {
	if x != nil {
		return x.SaleStatus
	}
	return 0
}

var File_land_proto protoreflect.FileDescriptor

const file_land_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"land.proto\x12\x04land\"'\n" +
	"\rgetLandRepReq\x12\x16\n" +
	"\x06LandID\x18\x01 \x01(\x03R\x06LandID\"1\n" +
	"\x0egetLandRepResp\x12\x1f\n" +
	"\vsale_status\x18\x01 \x01(\x03R\n" +
	"saleStatus2<\n" +
	"\x04land\x124\n" +
	"\agetLand\x12\x13.land.getLandRepReq\x1a\x14.land.getLandRepRespB\bZ\x06./landb\x06proto3"

var (
	file_land_proto_rawDescOnce sync.Once
	file_land_proto_rawDescData []byte
)

func file_land_proto_rawDescGZIP() []byte {
	file_land_proto_rawDescOnce.Do(func() {
		file_land_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_land_proto_rawDesc), len(file_land_proto_rawDesc)))
	})
	return file_land_proto_rawDescData
}

var file_land_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_land_proto_goTypes = []any{
	(*GetLandRepReq)(nil),  // 0: land.getLandRepReq
	(*GetLandRepResp)(nil), // 1: land.getLandRepResp
}
var file_land_proto_depIdxs = []int32{
	0, // 0: land.land.getLand:input_type -> land.getLandRepReq
	1, // 1: land.land.getLand:output_type -> land.getLandRepResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_land_proto_init() }
func file_land_proto_init() {
	if File_land_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_land_proto_rawDesc), len(file_land_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_land_proto_goTypes,
		DependencyIndexes: file_land_proto_depIdxs,
		MessageInfos:      file_land_proto_msgTypes,
	}.Build()
	File_land_proto = out.File
	file_land_proto_goTypes = nil
	file_land_proto_depIdxs = nil
}
