// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package couponModel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponFieldNames          = builder.RawFieldNames(&Coupon{})
	couponRows                = strings.Join(couponFieldNames, ",")
	couponRowsExpectAutoSet   = strings.Join(stringx.Remove(couponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponRowsWithPlaceHolder = strings.Join(stringx.Remove(couponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	couponModel interface {
		Insert(ctx context.Context, data *Coupon) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Coupon, error)
		Update(ctx context.Context, data *Coupon) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCouponModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Coupon struct {
		Id             int64     `db:"id"`
		DelState       int64     `db:"del_state"`       // 0-正常 1-删除
		DelTime        time.Time `db:"del_time"`        // 删除时间
		CreateTime     time.Time `db:"create_time"`     // 创建时间
		CouponId       int64     `db:"coupon_id"`       // 分类的分布式唯一ID
		CouponName     string    `db:"coupon_name"`     // 优惠券名称
		CouponType     string    `db:"coupon_type"`     // 优惠券类型
		ValidStart     time.Time `db:"valid_start"`     // 生效时间
		ValidEnd       time.Time `db:"valid_end"`       // 失效时间
		MinSpend       float64   `db:"min_spend"`       // 最低消费金额（门槛）
		Overlay        int64     `db:"overlay"`         // 是否可以叠加 0-否 1-是
		DiscountAmount float64   `db:"discount_amount"` // 折扣金额
		Discount       float64   `db:"discount"`        // 折扣比例
		Status         int64     `db:"status"`          // 1-可以使用 2-已经使用 3-已过期
	}
)

func newCouponModel(conn sqlx.SqlConn) *defaultCouponModel {
	return &defaultCouponModel{
		conn:  conn,
		table: "`coupon`",
	}
}

func (m *defaultCouponModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCouponModel) FindOne(ctx context.Context, id int64) (*Coupon, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponRows, m.table)
	var resp Coupon
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponModel) Insert(ctx context.Context, data *Coupon) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, couponRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DelState, data.DelTime, data.CouponId, data.CouponName, data.CouponType, data.ValidStart, data.ValidEnd, data.MinSpend, data.Overlay, data.DiscountAmount, data.Discount, data.Status)
	return ret, err
}

func (m *defaultCouponModel) Update(ctx context.Context, data *Coupon) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DelState, data.DelTime, data.CouponId, data.CouponName, data.CouponType, data.ValidStart, data.ValidEnd, data.MinSpend, data.Overlay, data.DiscountAmount, data.Discount, data.Status, data.Id)
	return err
}

func (m *defaultCouponModel) tableName() string {
	return m.table
}
