// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Activity struct {
	ActivityID int      `json:"activity_id"`
	FarmID     int      `json:"farm_id"`
	MainPic    string   `json:"main_pic"`
	ImageURLs  []string `json:"image_urls"`
	Title      string   `json:"title"`
	Text       string   `json:"text"`
	StartTime  string   `json:"start_time"`
	EndTime    string   `json:"end_time"`
}

type AddCommentReplyRequest struct {
	CommentReply CommentReply `json:"comment_reply"`
}

type AddCommentReplyResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type AddCommentRequest struct {
	Comment Comment `json:"comment"`
}

type AddCommentResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Category struct {
	CategoryID   int    `json:"category_id"`
	Name         string `json:"name"`
	CategoryType int    `json:"category_type"`
	Text         string `json:"text"`
	ImageUrl     string `json:"image_url"`
}

type Comment struct {
	ID              int    `json:"id"`
	CreateTime      string `json:"create_time"`
	TEXT            string `json:"text"`
	CommentID       int    `json:"comment_id"`
	GoodID          int    `json:"good_id"`
	LandID          int    `json:"land_id"`
	UserID          int    `json:"user_id"`
	Avatar          string `json:"avatar"`
	Nickname        string `json:"nickname"`
	CommentReplyNum int    `json:"comment_reply_num"`
}

type CommentReply struct {
	ID             int    `json:"id"`
	CreateTime     string `json:"create_time"`
	CommentID      int    `json:"comment_id"`
	CommentReplyID int    `json:"comment_reply_id"`
	ReplyTo        string `json:"reply_to"`
	TEXT           string `json:"text"`
	UserID         int    `json:"user_id"`
	Avatar         string `json:"avatar"`
	Nickname       string `json:"nickname"`
}

type GetActivityDetailRequest struct {
	ActivityID int `json:"activity_id"`
}

type GetActivityDetailResponse struct {
	Code       int      `json:"code"`
	Msg        string   `json:"msg"`
	Activities Activity `json:"activities"`
}

type GetCategoryRequest struct {
	CategoryType int `json:"categoryType"`
}

type GetCategoryResponse struct {
	Category []*Category `json:"category"`
	Code     int         `json:"code"`
	Msg      string      `json:"msg"`
}

type GetCommentReplyRequest struct {
	CommentID int `json:"comment_id"`
}

type GetCommentReplyResponse struct {
	Code           int             `json:"code"`
	Msg            string          `json:"msg"`
	CommentReplies []*CommentReply `json:"comment_reply"`
}

type GetCommentRequest struct {
	GoodID int `json:"good_id"`
	LandID int `json:"land_id"`
}

type GetCommentResponse struct {
	Code     int        `json:code"`
	Msg      string     `json:"msg"`
	Comments []*Comment `json:"comments"`
}

type GetGoodRequest struct {
	UserID int `json:"user_id"`
	GoodID int `json:"good_id"`
}

type GetGoodResponse struct {
	Code int    `json:"code"` // 状态码
	Msg  string `json:"msg"`  // 响应信息
	Good Good   `json:"good"` // 商品列表
}

type GetGoodsByTagRequest struct {
	UserID  int    `json:"user_id"`
	GoodTag string `json:"good_tag"`
}

type GetGoodsByTagResponse struct {
	Code  int     `json:"code"`       // 状态码
	Msg   string  `json:"msg"`        // 响应信息
	Goods []*Good `json:"goods_list"` // 商品列表
}

type GetGoodsRequest struct {
	UserID int `json:"user_id"`
}

type GetGoodsResponse struct {
	Code  int     `json:"code"`       // 状态码
	Msg   string  `json:"msg"`        // 响应信息
	Goods []*Good `json:"goods_list"` // 商品列表
}

type GetLandRequest struct {
	UserID int `json:"user_id"`
	LandID int `json:"land_id"`
}

type GetLandResponse struct {
	Code int    `json:"code"` // 状态码
	Msg  string `json:"msg"`  // 响应信息
	Land Land   `json:"land"` // 商品列表
}

type GetLandsByTagRequest struct {
	UserID  int    `json:"user_id"`
	LandTag string `json:"land_tag"`
}

type GetLandsByTagResponse struct {
	Code  int     `json:"code"`       // 状态码
	Msg   string  `json:"msg"`        // 响应信息
	Lands []*Land `json:"lands_list"` // 商品列表
}

type GetLandsRequest struct {
	UserID int `json:"user_id"`
}

type GetLandsResponse struct {
	Code  int     `json:"code"`       // 状态码
	Msg   string  `json:"msg"`        // 响应信息
	Lands []*Land `json:"lands_list"` // 商品列表
}

type GetMainPicRequest struct {
	FarmID int `json:"farm_id"`
}

type GetMainPicResponse struct {
	Code        int      `json:"code"`
	Msg         string   `json:"msg"`
	ActivityIDs []int    `json:"activity_ids"`
	MainPics    []string `json:"main_pics"`
	Title       []string `json:"title"`
}

type Good struct {
	Id         int64    `json:"id"`          // 主键ID
	DelState   int64    `json:"del_state"`   // 0-正常 1-删除
	DelTime    string   `json:"del_time"`    // 删除时间
	CreateTime string   `json:"create_time"` // 创建时间
	GoodId     int64    `json:"good_id"`     // 分布式唯一ID
	Title      string   `json:"title"`       // 商品名称
	GoodTag    string   `json:"good_tag"`    // 商品标签
	FarmId     int64    `json:"farm_id"`     // 所属农场ID
	ImageUrls  []string `json:"image_urls"`  // 图片信息（JSON字符串或逗号分隔）
	Price      float64  `json:"price"`       // 价格
	Units      string   `json:"units"`       // 单位，如个/斤/千克等
	Repertory  float64  `json:"repertory"`   // 库存
	Detail     string   `json:"detail"`      // 商品详情
}

type Land struct {
	Id         int64    `json:"id"`          // 主键ID
	DelState   int64    `json:"del_state"`   // 0-正常 1-删除
	DelTime    string   `json:"del_time"`    // 删除时间
	CreateTime string   `json:"create_time"` // 创建时间
	LandId     int64    `json:"land_id"`     // 分布式唯一ID
	FarmId     int64    `json:"farm_id"`     // 土地所属农场id
	LandName   string   `json:"land_name"`   // 土地名称
	LandTag    string   `json:"land_tag"`
	Area       string   `json:"area"`        // 土地面积
	ImageUrls  []string `json:"image_urls"`  // 图片信息
	Price      float64  `json:"price"`       // 价格
	Detail     string   `json:"detail"`      // 详情
	SaleStatus int64    `json:"sale_status"` // 租赁状态 0-出售中 1-已被租赁
	SaleTime   string   `json:"sale_time"`   // 租赁剩余时间
}

type SearchProductRequest struct {
	KeyWord string `json:"keyword"`
}

type SearchProductResponse struct {
	Code  int     `json:"code"`
	Msg   string  `json:"msg"`
	Goods []*Good `json:"goods"`
	Lands []*Land `json:"lands"`
}
