// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	detail "Server_gozero/BS/api/internal/handler/detail"
	user "Server_gozero/BS/api/internal/handler/user"
	"Server_gozero/BS/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/uploadUserInfo",
				Handler: detail.UploadUserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/userLogin",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/userRegister",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
