// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	farm "Server_gozero/BS/api/internal/handler/farm"
	login "Server_gozero/BS/api/internal/handler/login"
	userCenter "Server_gozero/BS/api/internal/handler/userCenter"
	"Server_gozero/BS/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/bindFarm",
				Handler: farm.BindFarmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getFarm",
				Handler: farm.GetFarmHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/userLogin",
				Handler: login.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getAdminInfo",
				Handler: userCenter.GetAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateAdmin",
				Handler: userCenter.UpdateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updatePass",
				Handler: userCenter.UpdatePassHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updatePhoneNumber",
				Handler: userCenter.UpdatePhoneNumberHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
