// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: BS.proto

package server

import (
	"context"

	"Server_gozero/BS/rpc/BSRPC"
	"Server_gozero/BS/rpc/internal/logic"
	"Server_gozero/BS/rpc/internal/svc"
)

type BSServer struct {
	svcCtx *svc.ServiceContext
	BSRPC.UnimplementedBSServer
}

func NewBSServer(svcCtx *svc.ServiceContext) *BSServer {
	return &BSServer{
		svcCtx: svcCtx,
	}
}

func (s *BSServer) AddUser(ctx context.Context, in *BSRPC.AddUserReq) (*BSRPC.AddUserResp, error) {
	l := logic.NewAddUserLogic(ctx, s.svcCtx)
	return l.AddUser(in)
}

func (s *BSServer) AddLandData(ctx context.Context, in *BSRPC.AddLandDataReq) (*BSRPC.AddLandDataResp, error) {
	l := logic.NewAddLandDataLogic(ctx, s.svcCtx)
	return l.AddLandData(in)
}

func (s *BSServer) AddGoodData(ctx context.Context, in *BSRPC.AddGoodDataReq) (*BSRPC.AddGoodDataResp, error) {
	l := logic.NewAddGoodDataLogic(ctx, s.svcCtx)
	return l.AddGoodData(in)
}
