// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: BS.proto

package server

import (
	"Server_gozero/BS/rpc/BSRPC"
	"context"

	"Server_gozero/BS/rpc/BS"
	"Server_gozero/BS/rpc/internal/logic"
	"Server_gozero/BS/rpc/internal/svc"
)

type SaleDataServer struct {
	svcCtx *svc.ServiceContext
	BSRPC.UnimplementedBSServer
}

func NewSaleDataServer(svcCtx *svc.ServiceContext) *SaleDataServer {
	return &SaleDataServer{
		svcCtx: svcCtx,
	}
}

func (s *SaleDataServer) AddUser(ctx context.Context, in *BS.AddUserReq) (*BS.AddUserResp, error) {
	l := logic.NewAddUserLogic(ctx, s.svcCtx)
	return l.AddUser(in)
}

func (s *SaleDataServer) AddLandData(ctx context.Context, in *BS.AddLandDataReq) (*BS.AddLandDataResp, error) {
	l := logic.NewAddLandDataLogic(ctx, s.svcCtx)
	return l.AddLandData(in)
}

func (s *SaleDataServer) AddGoodData(ctx context.Context, in *BS.AddGoodDataReq) (*BS.AddGoodDataResp, error) {
	l := logic.NewAddGoodDataLogic(ctx, s.svcCtx)
	return l.AddGoodData(in)
}
