// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	good "Server_gozero/CS/commodityServer/api/internal/handler/good"
	land "Server_gozero/CS/commodityServer/api/internal/handler/land"
	search "Server_gozero/CS/commodityServer/api/internal/handler/search"
	"Server_gozero/CS/commodityServer/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getAllGoods",
				Handler: good.GetAllGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getGood",
				Handler: good.GetGoodHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getGoodsByTag",
				Handler: good.GetGoodsByTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getAllLands",
				Handler: land.GetAllLandsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getLand",
				Handler: land.GetLandHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getLandsByTag",
				Handler: land.GetLandsByTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/searchProduct",
				Handler: search.SearchProductHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
