// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: ISender.proto

package id

import (
	ISender2 "Server_gozero/CS/common/ISender/ISender"
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetIDReq  = ISender2.GetIDReq
	GetIDResp = ISender2.GetIDResp

	ID interface {
		GetID(ctx context.Context, in *GetIDReq, opts ...grpc.CallOption) (*GetIDResp, error)
	}

	defaultID struct {
		cli zrpc.Client
	}
)

func NewID(cli zrpc.Client) ID {
	return &defaultID{
		cli: cli,
	}
}

func (m *defaultID) GetID(ctx context.Context, in *GetIDReq, opts ...grpc.CallOption) (*GetIDResp, error) {
	client := ISender2.NewIDClient(m.cli.Conn())
	return client.GetID(ctx, in, opts...)
}
