// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: good.proto

package server

import (
	"context"

	"Server_gozero/CS/commodityServer/good/rpc/good"
	"Server_gozero/CS/commodityServer/good/rpc/internal/logic"
	"Server_gozero/CS/commodityServer/good/rpc/internal/svc"
)

type GoodServer struct {
	svcCtx *svc.ServiceContext
	good.UnimplementedGoodServer
}

func NewGoodServer(svcCtx *svc.ServiceContext) *GoodServer {
	return &GoodServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodServer) GetGood(ctx context.Context, in *good.GetGoodRepReq) (*good.GetGoodRepResp, error) {
	l := logic.NewGetGoodLogic(ctx, s.svcCtx)
	return l.GetGood(in)
}
