// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6-devel
// 	protoc        v5.27.3
// source: good.proto

package good

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGoodRepReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodID        int64                  `protobuf:"varint,1,opt,name=GoodID,proto3" json:"GoodID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodRepReq) Reset() {
	*x = GetGoodRepReq{}
	mi := &file_good_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodRepReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodRepReq) ProtoMessage() {}

func (x *GetGoodRepReq) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodRepReq.ProtoReflect.Descriptor instead.
func (*GetGoodRepReq) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{0}
}

func (x *GetGoodRepReq) GetGoodID() int64 {
	if x != nil {
		return x.GoodID
	}
	return 0
}

type GetGoodRepResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repertory     float64                `protobuf:"fixed64,1,opt,name=repertory,proto3" json:"repertory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodRepResp) Reset() {
	*x = GetGoodRepResp{}
	mi := &file_good_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodRepResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodRepResp) ProtoMessage() {}

func (x *GetGoodRepResp) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodRepResp.ProtoReflect.Descriptor instead.
func (*GetGoodRepResp) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{1}
}

func (x *GetGoodRepResp) GetRepertory() float64 {
	if x != nil {
		return x.Repertory
	}
	return 0
}

var File_good_proto protoreflect.FileDescriptor

const file_good_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"good.proto\x12\x04good\"'\n" +
	"\rgetGoodRepReq\x12\x16\n" +
	"\x06GoodID\x18\x01 \x01(\x03R\x06GoodID\".\n" +
	"\x0egetGoodRepResp\x12\x1c\n" +
	"\trepertory\x18\x01 \x01(\x01R\trepertory2<\n" +
	"\x04good\x124\n" +
	"\agetGood\x12\x13.good.getGoodRepReq\x1a\x14.good.getGoodRepRespB\bZ\x06./goodb\x06proto3"

var (
	file_good_proto_rawDescOnce sync.Once
	file_good_proto_rawDescData []byte
)

func file_good_proto_rawDescGZIP() []byte {
	file_good_proto_rawDescOnce.Do(func() {
		file_good_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_good_proto_rawDesc), len(file_good_proto_rawDesc)))
	})
	return file_good_proto_rawDescData
}

var file_good_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_good_proto_goTypes = []any{
	(*GetGoodRepReq)(nil),  // 0: good.getGoodRepReq
	(*GetGoodRepResp)(nil), // 1: good.getGoodRepResp
}
var file_good_proto_depIdxs = []int32{
	0, // 0: good.good.getGood:input_type -> good.getGoodRepReq
	1, // 1: good.good.getGood:output_type -> good.getGoodRepResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_good_proto_init() }
func file_good_proto_init() {
	if File_good_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_good_proto_rawDesc), len(file_good_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_good_proto_goTypes,
		DependencyIndexes: file_good_proto_depIdxs,
		MessageInfos:      file_good_proto_msgTypes,
	}.Build()
	File_good_proto = out.File
	file_good_proto_goTypes = nil
	file_good_proto_depIdxs = nil
}
