// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: good.proto

package good

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Good interface {
		GetGood(ctx context.Context, in *GetGoodRepReq, opts ...grpc.CallOption) (*GetGoodRepResp, error)
		UpdateRep(ctx context.Context, in *UpdateRepReq, opts ...grpc.CallOption) (*UpdateRepResp, error)
	}

	defaultGood struct {
		cli zrpc.Client
	}
)

func NewGood(cli zrpc.Client) Good {
	return &defaultGood{
		cli: cli,
	}
}

func (m *defaultGood) GetGood(ctx context.Context, in *GetGoodRepReq, opts ...grpc.CallOption) (*GetGoodRepResp, error) {
	client := NewGoodClient(m.cli.Conn())
	return client.GetGood(ctx, in, opts...)
}

func (m *defaultGood) UpdateRep(ctx context.Context, in *UpdateRepReq, opts ...grpc.CallOption) (*UpdateRepResp, error) {
	client := NewGoodClient(m.cli.Conn())
	return client.UpdateRep(ctx, in, opts...)
}
