// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	GoodOrder "Server_gozero/CS/orderServer/api/internal/handler/GoodOrder"
	LandOrder "Server_gozero/CS/orderServer/api/internal/handler/LandOrder"
	WechatPay "Server_gozero/CS/orderServer/api/internal/handler/WechatPay"
	WechatPayHdl "Server_gozero/CS/orderServer/api/internal/handler/WechatPayHdl"
	"Server_gozero/CS/orderServer/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/AddGoodOrder",
				Handler: GoodOrder.AddGoodOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetGoodOrder",
				Handler: GoodOrder.GetGoodOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetGoodOrderByStatus",
				Handler: GoodOrder.GetGoodOrderByStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetGoodOrderDetail",
				Handler: GoodOrder.GetGoodOrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/UpdateGoodOrderCount",
				Handler: GoodOrder.UpdateGoodOrderCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/AddLandOrder",
				Handler: LandOrder.AddLandOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetLandOrder",
				Handler: LandOrder.GetLandOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetLandOrderByStatus",
				Handler: LandOrder.GetLandOrderByStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/GetLandOrderDetail",
				Handler: LandOrder.GetLandOrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/UpdateLandOrderCount",
				Handler: LandOrder.UpdateLandOrderCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/WechatOrder",
				Handler: WechatPay.WechatOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/WechatOrderHandler",
				Handler: WechatPayHdl.WechatOrderHdlHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
