// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: ISender.proto

package server

import (
	ISender2 "Server_gozero/CS/common/ISender/ISender"
	"Server_gozero/CS/common/ISender/internal/logic"
	"Server_gozero/CS/common/ISender/internal/svc"
	"context"
)

type IDServer struct {
	svcCtx *svc.ServiceContext
	ISender2.UnimplementedIDServer
}

func NewIDServer(svcCtx *svc.ServiceContext) *IDServer {
	return &IDServer{
		svcCtx: svcCtx,
	}
}

func (s *IDServer) GetID(ctx context.Context, in *ISender2.GetIDReq) (*ISender2.GetIDResp, error) {
	l := logic.NewGetIDLogic(ctx, s.svcCtx)
	return l.GetID(in)
}
