// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"Server_gozero/CS/commodityServer/good/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getAllGoods",
				Handler: GetAllGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getGood",
				Handler: GetGoodHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getGoodsByTag",
				Handler: getGoodsByTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
