// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"Server_gozero/CS/commodityServer/land/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getAllLands",
				Handler: GetAllLandsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getLand",
				Handler: GetLandHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getLandsByTag",
				Handler: getLandsByTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
