// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type LoginRequest struct {
	PhoneNumber string `json:"phone_number"`
	Password    string `json:password"`
}

type LoginResponse struct {
	Code         int    `json:"code"`
	Msg          string `json:"msg"`
	Admin        admin  `json:"admin"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int    `json:"accessExpire"`
	RefreshAfter int    `json:"refreshAfter"`
}

type Admin struct {
	AdminID     int    `json:"admin_id"`
	PhoneNumber string `json:"phone_number"`
	Avatar      string `json:"avatar"`
	Nickname    string `json:"nickname"`
	QQEmail     string `json:"qq_email"`
	Gender      int    `json:"gender"`
	FarmID      int    `json:"farm_id"`
}
