// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Activity struct {
	ActivityID int      `json:"activity_id"`
	FarmID     int      `json:"farm_id"`
	MainPic    string   `json:"main_pic"`
	ImageURLs  []string `json:"image_urls"`
	Title      string   `json:"title"`
	Text       string   `json:"text"`
	StartTime  string   `json:"start_time"`
	EndTime    string   `json:"end_time"`
}

type AddActivityRequest struct {
	Activity Activity `json:"activity"`
}

type AddActivityResponse struct {
	ActivityID int    `json:"activity_id"`
	Code       int    `json:"code"`
	Msg        string `json:"msg"`
}

type AddMainPicRequest struct {
	FarmID     int `form:"farm_id"`
	ActivityID int `form:"activity_id"`
}

type AddMainPicResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type AddPicRequest struct {
	FarmID     int `form:"farm_id"`
	ActivityID int `form:"activity_id"`
}

type AddPicResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type AddProductRequest struct {
	ProductType int  `json:"product_type"`
	FarmID      int  `json:"farm_id"`
	Good        Good `json:"good"`
	Land        Land `json:"land"`
}

type AddProductResponse struct {
	GoodID int    `json:"good_id"`
	LandID int    `json:"land_id"`
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
}

type Admin struct {
	AdminID     int    `json:"admin_id"`
	PhoneNumber string `json:"phone_number"`
	Avatar      string `json:"avatar"`
	NickName    string `json:"nickname"`
	QQEmail     string `json:"qq_email"`
	Gender      int    `json:"gender"`
	FarmID      int    `json:"farm_id"`
}

type BindFarm struct {
	FarmName     string `json:"farm_name"`
	Description  string `json:"description"`
	Address      string `json:"address"`
	LogoURL      string `json:"logo_url"`
	ImageURLs    []byte `json:"image_urls"`
	ContactPhone string `json:"contact_phone"`
}

type BindFarmRequest struct {
	AdminID  int      `json:"admin_id"`
	BindFarm BindFarm `json:"bind_farm"`
}

type BindFarmResponse struct {
	Code int    `json"code"`
	Msg  string `json"msg"`
}

type DelProductRequest struct {
	FarmID      int `json:"farm_id"`
	ProductType int `json:"product_type"`
	GoodID      int `json:"good_id"`
	LandID      int `json:"land_id"`
}

type DelProductResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Farm struct {
	FarmID       int    `json:"farm_id"`
	FarmName     string `json:"farm_name"`
	Description  string `json:"description"`
	Address      string `json:"address"`
	LogoURL      string `json:"logo_url"`
	ImageURLs    []byte `json:"image_urls"`
	ContactPhone string `json:"contact_phone"`
}

type GetActivityDetailRequest struct {
	ActivityID int `json:"activity_id"`
}

type GetActivityDetailResponse struct {
	Code       int      `json:"code"`
	Msg        string   `json:"msg"`
	Activities Activity `json:"activities"`
}

type GetAdminInfoRequest struct {
	AdminID int `json:"admin_id"`
}

type GetAdminInfoResponse struct {
	Code  int    `json:"code"`
	Msg   string `json:"msg"`
	Admin Admin  `json:"admin"`
}

type GetFarmRequest struct {
	AdminID int `json:"admin_id"`
}

type GetFarmResponse struct {
	Code int    `json:"code"`
	Msg  string `json"msg"`
	Farm Farm   `json"farm"`
}

type GetGoodOrderRequest struct {
	FarmID int `json:"farm_id"`
}

type GetGoodOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Good_order []*GoodOrder `json:"good_order"`
}

type GetLandOrderRequest struct {
	FarmID int `json:"farm_id"`
}

type GetLandOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Land_order []*LandOrder `json:"land_order"`
}

type GetLastOneYearSaleDataRequest struct {
	FarmID int `json:"farm_id"`
}

type GetLastOneYearSaleDataResponse struct {
	Code            int         `json:"code"`
	Msg             string      `json:"msg"`
	OneYearSaleData []*SaleData `json:"one_year_sale_data"`
}

type GetMainPicRequest struct {
	FarmID int `json:"farm_id"`
}

type GetMainPicResponse struct {
	Code        int      `json:"code"`
	Msg         string   `json:"msg"`
	ActivityIDs []int    `json:"activity_ids"`
	MainPics    []string `json:"main_pics"`
	Title       []string `json:"title"`
}

type GetProductRequest struct {
	ProductType int `json:"product_type"`
	FarmID      int `json:"farm_id"`
}

type GetProductResponse struct {
	Code int     `json:"code"`
	Msg  string  `json:"msg"`
	Good []*Good `json:"good"`
	Land []*Land `json:"land"`
}

type GetTotalDataRequest struct {
	FarmID int `json:"farm_id"`
}

type GetTotalDataResponse struct {
	Code           int     `json:"code"`
	Msg            string  `json:"msg"`
	GoodOrderCount int     `json:"good_order_count"`
	LandOrderCount int     `json:"sale_order_count"`
	GoodSaleCount  float64 `json:"good_sale_count"` // 农产品订单总销售额
	LandSaleCount  float64 `json:"land_sale_count"` // 土地订单总销售额
	SysUseCount    int     `json:"sys_use_count"`
}

type Good struct {
	ID         int      `json:"id"`
	DelState   int      `json:"del_state"`
	DelTime    string   `json:"del_time"`
	CreateTime string   `json:"create_time"`
	GoodID     int      `json:"good_id"`
	GoodTag    string   `json:"good_tag"`
	GoodName   string   `json:"good_name"`
	FarmID     int      `json:"farm_id"`
	ImageURLs  []string `json:"image_urls"`
	Price      float64  `json:"price"`
	Units      string   `json:"units"`
	Repertory  float64  `json:"repertory"`
	Detail     string   `json:"detail"`
}

type GoodOrder struct {
	Id          int64   `json:"id"`
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	GoodOrderId int64   `json:"good_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息（JSON字符串或逗号分隔）
	GoodId      int64   `json:"good_id"`       // 关联商品ID
	FarmId      int64   `json:"farm_id"`       // 商品所属农场ID
	UserId      int64   `json:"user_id"`       // 关联用户ID
	UserAddress string  `json:"user_address"`  // 用户所在地址
	FarmAddress string  `json:"farm_address"`  // 农场所在地址
	Price       float64 `json:"price"`         // 价格
	Units       string  `json:"units"`         // 单位（个/斤/千克等）
	Count       int64   `json:"count"`         // 购买数量
	Detail      string  `json:"detail"`        // 订单详情
	OrderStatus string  `json:"order_status"`
}

type Land struct {
	ID         int      `json:"id"`
	DelState   int      `json:"del_state"`
	DelTime    string   `json:"del_time"`
	CreateTime string   `json:"create_time"`
	LandID     int      `json:"land_id"`
	FarmID     int      `json:"farm_id"`
	LandName   string   `json:"land_name"`
	LandTag    string   `json:"land_tag"`
	Area       string   `json:"area"`
	ImageURLs  []string `json:"image_urls"`
	Price      float64  `json:"price"`
	Detail     string   `json:"detail"`
	SaleStatus int      `json:"sale_status"`
	SaleTime   string   `json:"sale_time"`
}

type LandOrder struct {
	Id          int64   `json:"id"`            // 主键ID
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	LandOrderId int64   `json:"land_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息
	LandId      int64   `json:"land_id"`       // 关联土地ID
	FarmId      int64   `json:"farm_id"`       // 所属农场ID
	UserId      int64   `json:"user_id"`       // 用户ID
	FarmAddress string  `json:"farm_address"`  // 农场地址
	Price       float64 `json:"price"`         // 租赁价格
	Count       int64   `json:"count"`         // 租赁时长
	Detail      string  `json:"detail"`        // 订单详情
	OrderStatus string  `json:"order_status"`
}

type LoginRequest struct {
	PhoneNumber string `json:"phone_number"`
	Password    string `json:"password"`
}

type LoginResponse struct {
	Code         int    `json:"code"`
	Msg          string `json:"msg"`
	Admin        Admin  `json:"admin"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int    `json:"accessExpire"`
	RefreshAfter int    `json:"refreshAfter"`
}

type SaleData struct {
	Farm_id        int     `json:"farm_id"`          // 关联农场id
	StatDate       string  `json:"stat_date"`        // 日
	GoodOrderCount int     `json:"good_order_count"` // 农产品订单总数
	LandOrderCount int     `json:"land_order_count"` // 土地订单总数
	GoodSaleCount  float64 `json:"good_sale_count"`  // 农产品订单总销售额
	LandSaleCount  float64 `json:"land_sale_count"`  // 土地订单总销售额
	SysUseCount    int     `json:"sys_use_count"`    // 当前系统适用人数
}

type SaleSummaryRequest struct {
	FarmID    int    `json:"farm_id"`
	StartDate string `json:"start_date"` // 开始日期，格式: YYYY-MM-DD
	EndDate   string `json:"end_date"`   // 结束日期，格式: YYYY-MM-DD
}

type SaleSummaryResponse struct {
	Code     int         `json:"code"`
	Msg      string      `json:"msg"`
	SaleData []*SaleData `json:"sale_data"`
}

type TestRequest struct {
	FarmID int `form:"farm_id"`
	GoodID int `form:"good_id"`
	LandID int `form:"land_id"`
}

type TestResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateAdminRequest struct {
	AdminID  int    `json:"admin_id"` // 明确传入的管理员 ID
	NickName string `json:"nickname"`
	QQEmail  string `json:"qq_email"`
	Gender   int    `json:"gender"`
}

type UpdateAdminResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateAvatarRequest struct {
	AdminID int `form:"admin_id"`
}

type UpdateAvatarResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateFarmInfoRequest struct {
	Del    int  `json:"del"`
	Status int  `json:"status"`
	Farm   Farm `json:"farm"`
}

type UpdateFarmInfoResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdatePassRequest struct {
	AdminID  int    `json:"admin_id"`
	Password string `json:"password"`
}

type UpdatePassResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdatePhoneNumberRequest struct {
	AdminID     int    `json:"admin_id"`
	PhoneNumber string `json:"phone_number"`
	Password    string `json:"password"`
}

type UpdatePhoneNumberResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateProductRequest struct {
	FarmID      int  `json:"farm_id"`
	ProductType int  `json:"product_type"`
	Good        Good `json:"good"`
	Land        Land `json:"land"`
}

type UpdateProductResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
