// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type Admin struct {
	AdminID     int    `json:"admin_id"`
	PhoneNumber string `json:"phone_number"`
	Avatar      string `json:"avatar"`
	NickName    string `json:"nickname"`
	QQEmail     string `json:"qq_email"`
	Gender      int    `json:"gender"`
	FarmID      int    `json:"farm_id"`
}

type BindFarm struct {
	FarmName     string `json:"farm_name"`
	Description  string `json:"description"`
	Address      string `json:"address"`
	LogoURL      string `json:"logo_url"`
	ImageURLs    []byte `json:"image_urls"`
	ContactPhone string `json:"contact_phone"`
}

type BindFarmRequest struct {
	AdminID  int      `json:"admin_id"`
	BindFarm BindFarm `json:"bind_farm"`
}

type BindFarmResponse struct {
	Code int    `json"code"`
	Msg  string `json"msg"`
}

type Farm struct {
	FarmID       int    `json:"farm_id"`
	FarmName     string `json:"farm_name"`
	Description  string `json:"description"`
	Address      string `json:"address"`
	LogoURL      string `json:"logo_url"`
	ImageURLs    []byte `json:"image_urls"`
	ContactPhone string `json:"contact_phone"`
}

type GetAdminInfoRequest struct {
	AdminID int `json:"admin_id"`
}

type GetAdminInfoResponse struct {
	Code  int    `json:"code"`
	Msg   string `json:"msg"`
	Admin Admin  `json:"admin"`
}

type GetFarmRequest struct {
	AdminID int `json:"admin_id"`
}

type GetFarmResponse struct {
	Code int    `json:"code"`
	Msg  string `json"msg"`
	Farm Farm   `json"farm"`
}

type GetGoodOrderRequest struct {
	FarmID int `json:"farm_id"`
}

type GetGoodOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Good_order []*GoodOrder `json:"good_order"`
}

type GetLandOrderRequest struct {
	FarmID int `json:"farm_id"`
}

type GetLandOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Land_order []*LandOrder `json:"land_order"`
}

type GoodOrder struct {
	Id          int64   `json:"id"`
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	GoodOrderId int64   `json:"good_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息（JSON字符串或逗号分隔）
	GoodId      int64   `json:"good_id"`       // 关联商品ID
	FarmId      int64   `json:"farm_id"`       // 商品所属农场ID
	UserId      int64   `json:"user_id"`       // 关联用户ID
	UserAddress string  `json:"user_address"`  // 用户所在地址
	FarmAddress string  `json:"farm_address"`  // 农场所在地址
	Price       float64 `json:"price"`         // 价格
	Units       string  `json:"units"`         // 单位（个/斤/千克等）
	Count       int64   `json:"count"`         // 购买数量
	Detail      string  `json:"detail"`        // 订单详情
	OrderStatus string  `json:"order_status"`
}

type LandOrder struct {
	Id          int64   `json:"id"`            // 主键ID
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	LandOrderId int64   `json:"land_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息
	LandId      int64   `json:"land_id"`       // 关联土地ID
	FarmId      int64   `json:"farm_id"`       // 所属农场ID
	UserId      int64   `json:"user_id"`       // 用户ID
	FarmAddress string  `json:"farm_address"`  // 农场地址
	Price       float64 `json:"price"`         // 租赁价格
	Count       int64   `json:"count"`         // 租赁时长
	Detail      string  `json:"detail"`        // 订单详情
	OrderStatus string  `json:"order_status"`
}

type LoginRequest struct {
	PhoneNumber string `json:"phone_number"`
	Password    string `json:"password"`
}

type LoginResponse struct {
	Code         int    `json:"code"`
	Msg          string `json:"msg"`
	Admin        Admin  `json:"admin"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int    `json:"accessExpire"`
	RefreshAfter int    `json:"refreshAfter"`
}

type UpdateAdminRequest struct {
	AdminID  int    `json:"admin_id"` // 明确传入的管理员 ID
	Avatar   string `json:"avatar"`
	NickName string `json:"nickname"`
	QQEmail  string `json:"qq_email"`
	Gender   int    `json:"gender"`
}

type UpdateAdminResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateFarmInfoRequest struct {
	Del    int  `json:"del"`
	Status int  `json:"status"`
	Farm   Farm `json:"farm"`
}

type UpdateFarmInfoResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdatePassRequest struct {
	AdminID  int    `json:"admin_id"`
	Password string `json:"password"`
}

type UpdatePassResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdatePhoneNumberRequest struct {
	AdminID     int    `json:"admin_id"`
	PhoneNumber string `json:"phone_number"`
	Password    string `json:"password"`
}

type UpdatePhoneNumberResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
