// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: ISender.proto

package server

import (
	"context"

	"Server_gozero/master/ISender/rpc/ISender"
	"Server_gozero/master/ISender/rpc/internal/logic"
	"Server_gozero/master/ISender/rpc/internal/svc"
)

type IDServer struct {
	svcCtx *svc.ServiceContext
	ISender.UnimplementedIDServer
}

func NewIDServer(svcCtx *svc.ServiceContext) *IDServer {
	return &IDServer{
		svcCtx: svcCtx,
	}
}

func (s *IDServer) GetID(ctx context.Context, in *ISender.GetIDReq) (*ISender.GetIDResp, error) {
	l := logic.NewGetIDLogic(ctx, s.svcCtx)
	return l.GetID(in)
}
