// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AddLandOrderRequest struct {
	Land_order LandOrder `json:"land_order"`
}

type AddLandOrderResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type GetLandOrderDetailRequest struct {
	UserID      int `json:"user_id"`
	LandOrderID int `json:"land_order_id"`
}

type GetLandOrderDetailResponse struct {
	Code       int       `json:"code"`       // 状态码
	Msg        string    `json:"msg"`        // 响应信息
	Land_order LandOrder `json:"land_order"` // 商品列表
}

type GetLandOrderRequest struct {
	UserID int `json:"user_id"`
}

type GetLandOrderResponse struct {
	Code       int          `json:"code"`
	Msg        string       `json:"msg"`
	Land_order []*LandOrder `json:"land_order"`
}

type LandOrder struct {
	Id          int64   `json:"id"`            // 主键ID
	DelState    int64   `json:"del_state"`     // 0-正常 1-删除
	DelTime     string  `json:"del_time"`      // 删除时间
	CreateTime  string  `json:"create_time"`   // 创建时间
	LandOrderId int64   `json:"land_order_id"` // 分布式唯一ID
	ImageUrls   string  `json:"image_urls"`    // 图片信息
	LandId      int64   `json:"land_id"`       // 关联土地ID
	FarmId      int64   `json:"farm_id"`       // 所属农场ID
	UserId      int64   `json:"user_id"`       // 用户ID
	FarmAddress string  `json:"farm_address"`  // 农场地址
	Price       float64 `json:"price"`         // 租赁价格
	Count       int64   `json:"count"`         // 租赁时长
	Detail      string  `json:"detail"`        // 订单详情
}
