// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: land.proto

package server

import (
	"context"

	"Server_gozero/CS/commodityServer/land/rpc/internal/logic"
	"Server_gozero/CS/commodityServer/land/rpc/internal/svc"
	"Server_gozero/CS/commodityServer/land/rpc/land"
)

type LandServer struct {
	svcCtx *svc.ServiceContext
	land.UnimplementedLandServer
}

func NewLandServer(svcCtx *svc.ServiceContext) *LandServer {
	return &LandServer{
		svcCtx: svcCtx,
	}
}

func (s *LandServer) GetLand(ctx context.Context, in *land.GetLandRepReq) (*land.GetLandRepResp, error) {
	l := logic.NewGetLandLogic(ctx, s.svcCtx)
	return l.GetLand(in)
}

func (s *LandServer) UpdateStatus(ctx context.Context, in *land.UpdateStatusReq) (*land.UpdateStatusResp, error) {
	l := logic.NewUpdateStatusLogic(ctx, s.svcCtx)
	return l.UpdateStatus(in)
}
